#!/usr/bin/env python

#code for scanning a network to discover ip addresses and Mac

import scapy.all as scapy

def scan(ip):
    arp_request = scapy.ARP(pdst=ip)
    broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_broadcast = broadcast/arp_request
    answered_list = scapy.srp(arp_request_broadcast, timeout=1, verbose=False)[0]

    clients_list = []
    for element in answered_list:
        client_dic ={"ip": element[1].psrc, "mac": element[1].hwsrc}
        clients_list.append(client_dic)
    return clients_list

def print_result(result_lists):
    print("IP \t\t\t\t\t MAC ADDRESS\n----------------------------------------")
    for client in result_lists:
        print(client["ip"] + "\t\t" + client["mac"])

scan_result = scan("10.0.2.1/24")
print_result(scan_result)
